# Generated by Django 4.2 on 2025-10-04 09:39

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Tractors', 'Tractors'), ('Irrigation', 'Irrigation'), ('Seeds', 'Seeds'), ('Fertilizers', 'Fertilizers'), ('Tools', 'Tools'), ('Other', 'Other')], max_length=20)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Used - Like New', 'Used - Like New'), ('Used - Good', 'Used - Good'), ('Used - Fair', 'Used - Fair')], max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.equipment_image_path)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_date'],
            },
        ),
    ]
