# Generated by Django 4.2 on 2025-10-04 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
    ]
