# Generated by Django 4.2 on 2025-10-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_job_customuser_address_customuser_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('planting', 'Planting'), ('harvesting', 'Harvesting'), ('irrigation', 'Irrigation'), ('pest_control', 'Pest Control'), ('maintenance', 'Maintenance'), ('transport', 'Transport'), ('other', 'Other')], max_length=30),
        ),
    ]
