# Generated by Django 4.2 on 2025-12-20 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_labourrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabourEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('farmer_name', models.CharField(max_length=150)),
                ('wage_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('days_worked', models.PositiveIntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, help_text='Cash, Bank Transfer, UPI, etc.', max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('job_start_date', models.DateField()),
                ('job_end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='api.jobapplication')),
                ('labour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabourSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('planting', 'Planting'), ('harvesting', 'Harvesting'), ('irrigation', 'Irrigation'), ('pest_control', 'Pest Control'), ('plowing', 'Plowing'), ('fertilizing', 'Fertilizing'), ('pruning', 'Pruning'), ('livestock', 'Livestock Management'), ('machinery', 'Machinery Operation'), ('organic_farming', 'Organic Farming'), ('other', 'Other')], max_length=30)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner (0-1 years)'), ('intermediate', 'Intermediate (1-3 years)'), ('advanced', 'Advanced (3-5 years)'), ('expert', 'Expert (5+ years)')], max_length=20)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('certifications', models.TextField(blank=True, help_text='Comma-separated list of certifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('labour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('labour', 'skill_name')},
            },
        ),
    ]
